// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Manis
{
    public partial class ManisDbContextModel
    {
        private ManisDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("2ae0753d-d55b-43ad-8c66-9d4f8d8a1c32"), entityTypeCount: 3)
        {
        }

        partial void Initialize()
        {
            var userEntity = UserEntityEntityType.Create(this);
            var eventEntity = EventEntityEntityType.Create(this);
            var migrationEntity = MigrationEntityEntityType.Create(this);

            UserEntityEntityType.CreateAnnotations(userEntity);
            EventEntityEntityType.CreateAnnotations(eventEntity);
            MigrationEntityEntityType.CreateAnnotations(migrationEntity);

            AddAnnotation("ProductVersion", "10.0.1");
        }
    }
}
