// <auto-generated />
using Manis.CompiledModels;
using Manis.Services;
using Microsoft.EntityFrameworkCore.Infrastructure;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(ManisDbContext), typeof(ManisDbContextModel))]
