// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Manis.CompiledModels
{
    public partial class ManisDbContextModel
    {
        private ManisDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("80e9014f-fa9b-434f-acd2-f640632e77a9"), entityTypeCount: 3)
        {
        }

        partial void Initialize()
        {
            var userEntity = UserEntityEntityType.Create(this);
            var eventEntity = EventEntityEntityType.Create(this);
            var migrationEntity = MigrationEntityEntityType.Create(this);

            UserEntityEntityType.CreateAnnotations(userEntity);
            EventEntityEntityType.CreateAnnotations(eventEntity);
            MigrationEntityEntityType.CreateAnnotations(migrationEntity);

            AddAnnotation("ProductVersion", "10.0.1");
        }
    }
}
