// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using Manis.Models;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.ChangeTracking.Internal;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Sqlite.Storage.Internal;
using Microsoft.EntityFrameworkCore.Storage;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Manis.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class UserEntityEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Manis.Models.UserEntity",
                typeof(UserEntity),
                baseEntityType,
                propertyCount: 8,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(Guid),
                propertyInfo: typeof(UserEntity).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(UserEntity).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            id.SetGetter(
                Guid (UserEntity instance) => UserEntityUnsafeAccessors.Id(instance),
                bool (UserEntity instance) => UserEntityUnsafeAccessors.Id(instance) == new Guid("00000000-0000-0000-0000-000000000000"));
            id.SetSetter(
                UserEntity (UserEntity instance, Guid value) =>
                {
                    UserEntityUnsafeAccessors.Id(instance) = value;
                    return instance;
                });
            id.SetMaterializationSetter(
                UserEntity (UserEntity instance, Guid value) =>
                {
                    UserEntityUnsafeAccessors.Id(instance) = value;
                    return instance;
                });
            id.SetAccessors(
                Guid (IInternalEntry entry) => (entry.FlaggedAsStoreGenerated(0) ? entry.ReadStoreGeneratedValue<Guid>(0) : (entry.FlaggedAsTemporary(0) && UserEntityUnsafeAccessors.Id(((UserEntity)(entry.Entity))) == new Guid("00000000-0000-0000-0000-000000000000") ? entry.ReadTemporaryValue<Guid>(0) : UserEntityUnsafeAccessors.Id(((UserEntity)(entry.Entity))))),
                Guid (IInternalEntry entry) => UserEntityUnsafeAccessors.Id(((UserEntity)(entry.Entity))),
                Guid (IInternalEntry entry) => entry.ReadOriginalValue<Guid>(id, 0),
                Guid (IInternalEntry entry) => ((InternalEntityEntry)(entry)).ReadRelationshipSnapshotValue<Guid>(id, 0));
            id.SetPropertyIndexes(
                index: 0,
                originalValueIndex: 0,
                shadowIndex: -1,
                relationshipIndex: 0,
                storeGenerationIndex: 0);
            id.TypeMapping = SqliteGuidTypeMapping.Default;
            id.SetCurrentValueComparer(new EntryCurrentValueComparer<Guid>(id));

            var activationCode = runtimeEntityType.AddProperty(
                "ActivationCode",
                typeof(string),
                propertyInfo: typeof(UserEntity).GetProperty("ActivationCode", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(UserEntity).GetField("<ActivationCode>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 255);
            activationCode.SetGetter(
                string (UserEntity instance) => UserEntityUnsafeAccessors.ActivationCode(instance),
                bool (UserEntity instance) => UserEntityUnsafeAccessors.ActivationCode(instance) == null);
            activationCode.SetSetter(
                UserEntity (UserEntity instance, string value) =>
                {
                    UserEntityUnsafeAccessors.ActivationCode(instance) = value;
                    return instance;
                });
            activationCode.SetMaterializationSetter(
                UserEntity (UserEntity instance, string value) =>
                {
                    UserEntityUnsafeAccessors.ActivationCode(instance) = value;
                    return instance;
                });
            activationCode.SetAccessors(
                string (IInternalEntry entry) => UserEntityUnsafeAccessors.ActivationCode(((UserEntity)(entry.Entity))),
                string (IInternalEntry entry) => UserEntityUnsafeAccessors.ActivationCode(((UserEntity)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(activationCode, 1),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(activationCode));
            activationCode.SetPropertyIndexes(
                index: 1,
                originalValueIndex: 1,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            activationCode.TypeMapping = SqliteStringTypeMapping.Default;

            var email = runtimeEntityType.AddProperty(
                "Email",
                typeof(string),
                propertyInfo: typeof(UserEntity).GetProperty("Email", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(UserEntity).GetField("<Email>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 255);
            email.SetGetter(
                string (UserEntity instance) => UserEntityUnsafeAccessors.Email(instance),
                bool (UserEntity instance) => UserEntityUnsafeAccessors.Email(instance) == null);
            email.SetSetter(
                UserEntity (UserEntity instance, string value) =>
                {
                    UserEntityUnsafeAccessors.Email(instance) = value;
                    return instance;
                });
            email.SetMaterializationSetter(
                UserEntity (UserEntity instance, string value) =>
                {
                    UserEntityUnsafeAccessors.Email(instance) = value;
                    return instance;
                });
            email.SetAccessors(
                string (IInternalEntry entry) => UserEntityUnsafeAccessors.Email(((UserEntity)(entry.Entity))),
                string (IInternalEntry entry) => UserEntityUnsafeAccessors.Email(((UserEntity)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(email, 2),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(email));
            email.SetPropertyIndexes(
                index: 2,
                originalValueIndex: 2,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            email.TypeMapping = SqliteStringTypeMapping.Default;

            var isActivated = runtimeEntityType.AddProperty(
                "IsActivated",
                typeof(bool),
                propertyInfo: typeof(UserEntity).GetProperty("IsActivated", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(UserEntity).GetField("<IsActivated>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: false);
            isActivated.SetGetter(
                bool (UserEntity instance) => UserEntityUnsafeAccessors.IsActivated(instance),
                bool (UserEntity instance) => UserEntityUnsafeAccessors.IsActivated(instance) == false);
            isActivated.SetSetter(
                UserEntity (UserEntity instance, bool value) =>
                {
                    UserEntityUnsafeAccessors.IsActivated(instance) = value;
                    return instance;
                });
            isActivated.SetMaterializationSetter(
                UserEntity (UserEntity instance, bool value) =>
                {
                    UserEntityUnsafeAccessors.IsActivated(instance) = value;
                    return instance;
                });
            isActivated.SetAccessors(
                bool (IInternalEntry entry) => UserEntityUnsafeAccessors.IsActivated(((UserEntity)(entry.Entity))),
                bool (IInternalEntry entry) => UserEntityUnsafeAccessors.IsActivated(((UserEntity)(entry.Entity))),
                bool (IInternalEntry entry) => entry.ReadOriginalValue<bool>(isActivated, 3),
                bool (IInternalEntry entry) => entry.GetCurrentValue<bool>(isActivated));
            isActivated.SetPropertyIndexes(
                index: 3,
                originalValueIndex: 3,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            isActivated.TypeMapping = BoolTypeMapping.Default.Clone(
                comparer: new ValueComparer<bool>(
                    bool (bool v1, bool v2) => v1 == v2,
                    int (bool v) => ((object)v).GetHashCode(),
                    bool (bool v) => v),
                keyComparer: new ValueComparer<bool>(
                    bool (bool v1, bool v2) => v1 == v2,
                    int (bool v) => ((object)v).GetHashCode(),
                    bool (bool v) => v),
                providerValueComparer: new ValueComparer<bool>(
                    bool (bool v1, bool v2) => v1 == v2,
                    int (bool v) => ((object)v).GetHashCode(),
                    bool (bool v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "INTEGER"));

            var login = runtimeEntityType.AddProperty(
                "Login",
                typeof(string),
                propertyInfo: typeof(UserEntity).GetProperty("Login", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(UserEntity).GetField("<Login>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 255);
            login.SetGetter(
                string (UserEntity instance) => UserEntityUnsafeAccessors.Login(instance),
                bool (UserEntity instance) => UserEntityUnsafeAccessors.Login(instance) == null);
            login.SetSetter(
                UserEntity (UserEntity instance, string value) =>
                {
                    UserEntityUnsafeAccessors.Login(instance) = value;
                    return instance;
                });
            login.SetMaterializationSetter(
                UserEntity (UserEntity instance, string value) =>
                {
                    UserEntityUnsafeAccessors.Login(instance) = value;
                    return instance;
                });
            login.SetAccessors(
                string (IInternalEntry entry) => UserEntityUnsafeAccessors.Login(((UserEntity)(entry.Entity))),
                string (IInternalEntry entry) => UserEntityUnsafeAccessors.Login(((UserEntity)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(login, 4),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(login));
            login.SetPropertyIndexes(
                index: 4,
                originalValueIndex: 4,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            login.TypeMapping = SqliteStringTypeMapping.Default;

            var passwordHash = runtimeEntityType.AddProperty(
                "PasswordHash",
                typeof(string),
                propertyInfo: typeof(UserEntity).GetProperty("PasswordHash", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(UserEntity).GetField("<PasswordHash>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 512);
            passwordHash.SetGetter(
                string (UserEntity instance) => UserEntityUnsafeAccessors.PasswordHash(instance),
                bool (UserEntity instance) => UserEntityUnsafeAccessors.PasswordHash(instance) == null);
            passwordHash.SetSetter(
                UserEntity (UserEntity instance, string value) =>
                {
                    UserEntityUnsafeAccessors.PasswordHash(instance) = value;
                    return instance;
                });
            passwordHash.SetMaterializationSetter(
                UserEntity (UserEntity instance, string value) =>
                {
                    UserEntityUnsafeAccessors.PasswordHash(instance) = value;
                    return instance;
                });
            passwordHash.SetAccessors(
                string (IInternalEntry entry) => UserEntityUnsafeAccessors.PasswordHash(((UserEntity)(entry.Entity))),
                string (IInternalEntry entry) => UserEntityUnsafeAccessors.PasswordHash(((UserEntity)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(passwordHash, 5),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(passwordHash));
            passwordHash.SetPropertyIndexes(
                index: 5,
                originalValueIndex: 5,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            passwordHash.TypeMapping = SqliteStringTypeMapping.Default;

            var passwordHashMethod = runtimeEntityType.AddProperty(
                "PasswordHashMethod",
                typeof(string),
                propertyInfo: typeof(UserEntity).GetProperty("PasswordHashMethod", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(UserEntity).GetField("<PasswordHashMethod>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            passwordHashMethod.SetGetter(
                string (UserEntity instance) => UserEntityUnsafeAccessors.PasswordHashMethod(instance),
                bool (UserEntity instance) => UserEntityUnsafeAccessors.PasswordHashMethod(instance) == null);
            passwordHashMethod.SetSetter(
                UserEntity (UserEntity instance, string value) =>
                {
                    UserEntityUnsafeAccessors.PasswordHashMethod(instance) = value;
                    return instance;
                });
            passwordHashMethod.SetMaterializationSetter(
                UserEntity (UserEntity instance, string value) =>
                {
                    UserEntityUnsafeAccessors.PasswordHashMethod(instance) = value;
                    return instance;
                });
            passwordHashMethod.SetAccessors(
                string (IInternalEntry entry) => UserEntityUnsafeAccessors.PasswordHashMethod(((UserEntity)(entry.Entity))),
                string (IInternalEntry entry) => UserEntityUnsafeAccessors.PasswordHashMethod(((UserEntity)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(passwordHashMethod, 6),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(passwordHashMethod));
            passwordHashMethod.SetPropertyIndexes(
                index: 6,
                originalValueIndex: 6,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            passwordHashMethod.TypeMapping = SqliteStringTypeMapping.Default;

            var passwordSalt = runtimeEntityType.AddProperty(
                "PasswordSalt",
                typeof(string),
                propertyInfo: typeof(UserEntity).GetProperty("PasswordSalt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(UserEntity).GetField("<PasswordSalt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 128);
            passwordSalt.SetGetter(
                string (UserEntity instance) => UserEntityUnsafeAccessors.PasswordSalt(instance),
                bool (UserEntity instance) => UserEntityUnsafeAccessors.PasswordSalt(instance) == null);
            passwordSalt.SetSetter(
                UserEntity (UserEntity instance, string value) =>
                {
                    UserEntityUnsafeAccessors.PasswordSalt(instance) = value;
                    return instance;
                });
            passwordSalt.SetMaterializationSetter(
                UserEntity (UserEntity instance, string value) =>
                {
                    UserEntityUnsafeAccessors.PasswordSalt(instance) = value;
                    return instance;
                });
            passwordSalt.SetAccessors(
                string (IInternalEntry entry) => UserEntityUnsafeAccessors.PasswordSalt(((UserEntity)(entry.Entity))),
                string (IInternalEntry entry) => UserEntityUnsafeAccessors.PasswordSalt(((UserEntity)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(passwordSalt, 7),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(passwordSalt));
            passwordSalt.SetPropertyIndexes(
                index: 7,
                originalValueIndex: 7,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            passwordSalt.TypeMapping = SqliteStringTypeMapping.Default;

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            var id = runtimeEntityType.FindProperty("Id");
            var activationCode = runtimeEntityType.FindProperty("ActivationCode");
            var email = runtimeEntityType.FindProperty("Email");
            var isActivated = runtimeEntityType.FindProperty("IsActivated");
            var login = runtimeEntityType.FindProperty("Login");
            var passwordHash = runtimeEntityType.FindProperty("PasswordHash");
            var passwordHashMethod = runtimeEntityType.FindProperty("PasswordHashMethod");
            var passwordSalt = runtimeEntityType.FindProperty("PasswordSalt");
            var key = runtimeEntityType.FindKey(new[] { id });
            key.SetPrincipalKeyValueFactory(KeyValueFactoryFactory.CreateSimpleNonNullableFactory<Guid>(key));
            key.SetIdentityMapFactory(IdentityMapFactoryFactory.CreateFactory<Guid>(key));
            runtimeEntityType.SetOriginalValuesFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((UserEntity)(source.Entity));
                    return ((ISnapshot)(new Snapshot<Guid, string, string, bool, string, string, string, string>(((ValueComparer<Guid>)(((IProperty)id).GetValueComparer())).Snapshot(source.GetCurrentValue<Guid>(id)), (source.GetCurrentValue<string>(activationCode) == null ? null : ((ValueComparer<string>)(((IProperty)activationCode).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(activationCode))), (source.GetCurrentValue<string>(email) == null ? null : ((ValueComparer<string>)(((IProperty)email).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(email))), ((ValueComparer<bool>)(((IProperty)isActivated).GetValueComparer())).Snapshot(source.GetCurrentValue<bool>(isActivated)), (source.GetCurrentValue<string>(login) == null ? null : ((ValueComparer<string>)(((IProperty)login).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(login))), (source.GetCurrentValue<string>(passwordHash) == null ? null : ((ValueComparer<string>)(((IProperty)passwordHash).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(passwordHash))), (source.GetCurrentValue<string>(passwordHashMethod) == null ? null : ((ValueComparer<string>)(((IProperty)passwordHashMethod).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(passwordHashMethod))), (source.GetCurrentValue<string>(passwordSalt) == null ? null : ((ValueComparer<string>)(((IProperty)passwordSalt).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(passwordSalt))))));
                });
            runtimeEntityType.SetStoreGeneratedValuesFactory(
                ISnapshot () => ((ISnapshot)(new Snapshot<Guid>(((ValueComparer<Guid>)(((IProperty)id).GetValueComparer())).Snapshot(default(Guid))))));
            runtimeEntityType.SetTemporaryValuesFactory(
                ISnapshot (IInternalEntry source) => ((ISnapshot)(new Snapshot<Guid>(default(Guid)))));
            runtimeEntityType.SetShadowValuesFactory(
                ISnapshot (IDictionary<string, object> source) => Snapshot.Empty);
            runtimeEntityType.SetEmptyShadowValuesFactory(
                ISnapshot () => Snapshot.Empty);
            runtimeEntityType.SetRelationshipSnapshotFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((UserEntity)(source.Entity));
                    return ((ISnapshot)(new Snapshot<Guid>(((ValueComparer<Guid>)(((IProperty)id).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<Guid>(id)))));
                });
            runtimeEntityType.SetCounts(new PropertyCounts(
                propertyCount: 8,
                navigationCount: 0,
                complexPropertyCount: 0,
                complexCollectionCount: 0,
                originalValueCount: 8,
                shadowCount: 0,
                relationshipCount: 1,
                storeGeneratedCount: 1));
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "Users");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
