// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using Manis.Models;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Manis.CompiledModels
{
    public static class UserEntityUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Id>k__BackingField")]
        public static extern ref Guid Id(UserEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ActivationCode>k__BackingField")]
        public static extern ref string ActivationCode(UserEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Email>k__BackingField")]
        public static extern ref string Email(UserEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<IsActivated>k__BackingField")]
        public static extern ref bool IsActivated(UserEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Login>k__BackingField")]
        public static extern ref string Login(UserEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<PasswordHash>k__BackingField")]
        public static extern ref string PasswordHash(UserEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<PasswordHashMethod>k__BackingField")]
        public static extern ref string PasswordHashMethod(UserEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<PasswordSalt>k__BackingField")]
        public static extern ref string PasswordSalt(UserEntity @this);
    }
}
